# Header
site_title: Troy's Blog
site_description: Focus on Web Development and live in ChengDu. Happy Coding, Happy Life!
menu:
  Home: /
  Archives: /archives
  AboutMe: /about
# display widgets
widgets:
- archives
- recent_posts
- tagcloud
# widget behavior
archive_type: 'monthly'
show_count: false
# Content
excerpt_link: Read More