# Header
site_title: Troy's Blog
site_description: Focus on Web Development and live in ChengDu. Happy Coding, Happy Life!
menu:
  Home: /
  Archives: /archives
  AboutMe: /about
# Miscellaneous
favicon:
# display widgets
widgets:
- archives
- recent_posts
- tagcloud
# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# Disqus
disqus:
  enable: false
  shortname: troyyang-com
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: true
  shortname: troyyang